Repository OZ-Coding-School/oz_externship_fe_01_team2, pull requests merged in 2025-07, with the labels that each got.

#92 feat(#88): 마이페이지 UI 구현
  src/App.tsx
  src/components/common/Sidebar.tsx
  src/components/myPage/MypageCourse.tsx
  src/components/myPage/MypageProfile.tsx
  src/pages/MyPage.tsx
Labels: ✨feature

#95 feat(#89): 마이페이지 수정 UI 구현 및 FormInput disabled 추가
  package-lock.json
  src/App.tsx
  src/components/common/FormInput/FormInput.tsx
  src/components/common/FormInput/FormInput.types.ts
  src/pages/MypageEdit.tsx
Labels: ✨feature

#96 refactor(#79): Layout컴포넌트 리팩토링
  src/App.tsx
  src/components/common/Layout.tsx
  src/pages/Layout.tsx
Labels: ♻️ refactor

#98 fix(#97): github action CD workflow 수정
  .github/workflows/deploy.yml
Labels: 🐛 fix

#99 fix(#97): github action CD workflow, package.json 수정
  .github/workflows/deploy.yml
  package.json
Labels: 🐛 fix

#105 feat(#85): AIAnswer 컴포넌트 및 getAiAnswerStream 스트리밍 API 구현
  .gitignore
  src/api/getAiAnswerStream.ts
  src/assets/icons/message.png
  src/assets/images/qna/img_ai_avatar.png
  src/components/qna/AIAnswer.tsx
  src/components/qna/AIAnswerSkeleton.tsx
  src/pages/QnaDetailPage.tsx
  src/styles/animation.css
Labels: ✨feature

#104 feat(#5): 답변 등록 UI 구현
  src/components/Mocks/qnaData.ts
  src/components/common/MarkdownEditor/MarkdownEditor.tsx
  src/components/common/MarkdownEditor/MarkdownEditor.types.ts
  src/components/qna/AnswerForm.tsx
  src/pages/QnaDetailPage.tsx
  src/types/auth.ts
Labels: ✨feature

#111 feat(#86): AI Chatbot UI 구현
  src/assets/images/common/floating_btn_kakao.png
  src/components/common/AIChatbot/AIChatbot.tsx
  src/components/common/AIChatbot/index.ts
  src/components/common/Layout.tsx
Labels: ✨feature

#129 feat (#128): 마이페이지 API 연동 및 관련 코드 수정
  src/api/auth/api.ts
  src/api/auth/types.ts
  src/api/user-profile/api.ts
  src/api/user-profile/types.ts
  src/components/myPage/MypageProfile.tsx
  src/lib/fetcher.ts
  src/pages/MyPage.tsx
  src/pages/MypageEdit.tsx
  src/store/authStore.ts
  src/types/UserProfile.type.ts
Labels: ✨feature, ♻️ refactor

#132 feat(#124): 이메일 로그인 api
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
Labels: ✨feature

#142 feat(#120): 질문 상세조회 API 연동
  src/api/qna/questionApi.ts
  src/components/common/MarkdownEditor/MarkdownRenderer.tsx
  src/components/qna/AnswerCard.tsx
  src/components/qna/AnswerForm.tsx
  src/pages/QnaDetailPage.tsx
  src/styles/markdown.css
  src/types/qnaDetail.ts
Labels: ✨feature

#137 feat(#134): 비밀번호 찾기 인증코드 발송, 검증 API
  src/components/LoginForm/EmailVerification.tsx
  src/components/LoginForm/FindIdModal.tsx
  src/components/LoginForm/FindPwModal.tsx
  src/components/LoginForm/PhoneVerification.tsx
  src/components/LoginForm/RecoverAccountModal.tsx
  src/components/common/FormInput/FormInput.types.ts
  src/components/common/Popup/PwSuccess.tsx
  src/components/myPage/ChangePasswordForm.tsx
  src/constants/validation.ts
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
Labels: ✨feature

#145 feat(#106): 수강생 등록 모달 ui, api 연동
  src/components/LoginForm/RegisterModal.tsx
  src/components/common/Header.tsx
  src/components/common/SingleDropdown.tsx
Labels: ✨feature

#148 fix(#146): 로그인 성공 후 zustand 상태 업데이트
  src/pages/LoginPage.tsx
Labels: 🐛 fix, ♻️ refactor

#147 feat(#140): Header 컴포넌트 Auth 기능 추가
  src/components/common/Header.tsx
Labels: ✨feature

#159 feat(#157): 회원가입폼 api연동
  src/hooks/useSignApi.ts
  src/pages/SignUpFormPage.tsx
Labels: ✨feature

#170 fix(#168): CI/CD 워크플로우 수정(env 추가 등)
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  src/pages/QnaDetailPage.tsx
Labels: 🐛 fix

#173 Docs(#151): README 작성
  README.md
  public/팀사진.png
Labels: 📑 docs

#175 config(#174): 소셜 로그인 관련 환경변수 .env 설정 추가(Kakao, Naver)
  .github/workflows/deploy.yml
Labels: 📦 chore
